AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template to create Lambda functions.

Resources:
    convertobj:
    Type: AWS::Serverless::Function
        Properties:
          Handler: lambda_function.handler
          Runtime: Python 3.7
          Timeout: 20
          MemorySize: 512
          Events:
            s3Event:
              Type: S3
              Properties:
                Bucket: sandytes
                Events: s3:ObjectCreated:*

Policies:
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: '*'
            
            
 