AWSTemplateFormatVersion: '2010-09-09'
Description: Demo stack, creates one SSM parameter.
Parameters:
  ParamName:
    Type: String
  ParamDescription:
    Type: String
  EnvironmentType:
    Description: Name your EnvironmentType with name you want.
    Type: String
    AllowedValues:
        - dev
        - demo
        - prod
  ParamValue:
    Type: String
    Description: The value to store in the SSM parameter.
Resources:
  DemoParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub '${EnvironmentType}-Param'
      Type: "String"
      Value: !Ref ParamValue
      Description: !Ref ParamDescription
Outputs:
  DemoParameter:
    Description: The name of the demo parameter.
    Value: !Ref DemoParameter
